file = main.c
file += emplistsys.c
file += system.c

Display:
	@echo "The program is Running"

Compile: Display
	gcc $(file) -o Employee_System

run: Compile
	Employee_System.exe

clean:
	@cls
	@del Employee_System.exe
	@echo "The Employee_System.exe deleted"